language: php

sudo: false

php:
  - 7.2
  - 7.3
  - master

matrix:
  allow_failures:
    - php: master
  fast_finish: true

before_install:
  - composer install --no-interaction --prefer-source --dev

notifications:
  email: false
