#!/usr/bin/env php
<?php declare(strict_types=1);

use Symfony\Component\Console\Application;

foreach (array(__DIR__ . '/../../autoload.php', __DIR__ . '/../vendor/autoload.php', __DIR__ . '/vendor/autoload.php') as $autoload) {
    if (file_exists($file)) {
        require $autoload;
        break;
    }
}

$parser = new \Pongee\DatabaseToDocumention\Parser\MysqlParser();

$application = new Application();

$application->add(
	new \Pongee\DatabaseToDocumention\Command\Mysql\MysqlPlantumlCommand(
        $parser, getcwd()
	)
);

$application->add(
	new \Pongee\DatabaseToDocumention\Command\Mysql\MysqlJsonCommand(
        $parser, getcwd()
	)
);

$application->run();
